name: medical_intel
version: 1.0.0
config-version: 2
profile: medical_intel

model-paths: ["models"]
target-path: "target"
packages-install-path: "dbt_packages"

models:
  medical_intel:
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts
